services:
  - type: cron
    name: product-csv-generator
    schedule: "0 0 * * 5"  # Every Friday at midnight (UTC)
    runtime: python
    buildCommand: ""
    startCommand: "python cron/main.py"

  - type: web
    name: product-feed-web
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn web.app:app"
